### ISSUE TITLE
Am I missing something or is it a bug?

### ISSUE THREAD

**Issue by rajkrpan** [mlbright/edmonds#1]
Can you give an example of directed spanning tree. This concept is bit unclear to me. For example if I try this:

import edmonds
G={}
G[1]={2:1, 3:1, 4:1}
G[3]={1:1, 4:1}
edmonds.mst(1,G)
 {1: {2: 1, 3: 1, 4: 1}}

whereas 
G={}
G[1]={2:1, 3:1, 4:1}
edmonds.mst(1,G) 
returns none.

I thought that both the output should be same. Am I missing something? 
Thanks.

**Comment by mlbright** [comment]
hi there!

Thanks for your interest.  I have not looked at this code in a while, but I
think the problem is that the algorithm relies on there being a 'reverse'
graph, where the root node is a source node. In the second graph, the
reverse graph is a sink node without any destinations.

M-L

On Thu, Jan 12, 2012 at 12:19 PM, rajkrpan <
reply@reply.github.com

**Comment by rajkrpan** [comment]
I check the corresponding java code:

if (reverse.getAdjacent(root) != null) {
   reverse.getAdjacent(root).clear();}

Python equivalent should be:
    if root in RG:
        RG[root].clear()
instead of 
    if root not in RG:
        return None
    RG[root].clear()

**Comment by mlbright** [comment]
Give me a pull request, and I'll merge your changes. Thanks for looking at
this!

M-L

On Fri, Jan 13, 2012 at 3:25 AM, rajkrpan <
reply@reply.github.com
